name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Test Artifacts
        uses: actions/cache@v4
        with:
          path: .artifacts
          key: ${{ runner.os }}-artifacts-${{ hashFiles('**/Artifacts.java') }}

      - name: Install ffmpeg on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew build

      - name: Publish to Central Repository (${{ runner.os }})
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NCMP_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NCMP_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.NCMP_SECRET_KEY_ARMOR }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.NCMP_SECRET_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.NCMP_SECRET_KEY_PASSWORD }}

      - name: Archive logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-test-reports
          path: build/reports
