name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Test Artifacts
        uses: actions/cache@v3
        with:
          path: .artifacts
          key: ${{ runner.os }}-artifacts-${{ hashFiles('**/Artifacts.java') }}

      - name: Setup FFmpeg (${{ runner.os }})
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg-${{ runner.os }}

      - name: Build and test using gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --console=plain build

      - name: Publish to Central Repository
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --console=plain publish releaseNexusRepositories
          execution-only-caches: true
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.OSSRH_SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY_RING_BASE64: ${{ secrets.OSSRH_SIGNING_SECRET_KEY_RING_BASE64 }}

      - name: Archive logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-test-reports
          path: build/reports
