name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

permissions:
  checks: write

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ 17 ]
        ffmpeg-version: [ "6.0", "5.1.1", "4.4.1" ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Cache Test Artifacts
        uses: actions/cache@v3
        with:
          path: .artifacts
          key: ${{ runner.os }}-artifacts-${{ hashFiles('**/Artifacts.java') }}

      - name: Setup FFmpeg (${{ runner.os }})
        uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ffmpeg-version }}

      - name: Build (${{ runner.os }})
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --console=plain build

      - name: |
          Test Report (${{ runner.os }}, 
          JDK ${{ matrix.java-version }}, 
          FFmpeg ${{ matrix.ffmpeg-version }})
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: |
            Test Report (${{ runner.os }}, 
            JDK ${{ matrix.java-version }},
            FFmpeg ${{ matrix.ffmpeg-version }})
          reporter: java-junit
          path: '**/TEST-*.xml'
