name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  checks: write

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Test Artifacts
        uses: actions/cache@v3
        with:
          path: .artifacts
          key: artifacts-${{ hashFiles('**/Artifacts.java') }}

      - name: Setup FFmpeg (${{ runner.os }})
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Build (${{ runner.os }})
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --console=plain build

      - name: Test Report (${{ runner.os }})
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report (${{ runner.os }})
          reporter: java-junit
          path: '**/TEST-*.xml'
