name: Tests

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Test Artifacts
        uses: actions/cache@v4
        with:
          path: .artifacts
          key: artifacts-${{ hashFiles('**/Artifacts.java') }}

      - name: Install ffmpeg on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install ffmpeg on MacOS
        run: brew install ffmpeg
        if: startsWith(matrix.os, 'macos')

      - name: Install ffmpeg on Windows
        run: choco install ffmpeg
        if: startsWith(matrix.os, 'windows')

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build (${{ runner.os }})
        run: ./gradlew build

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        if: ${{ runner.os == 'Linux' }}

      - name: Test Report (${{ runner.os }})
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report (${{ runner.os }})
          reporter: java-junit
          path: '**/TEST-*.xml'
