name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  checks: write

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Test Artifacts
        uses: actions/cache@v4
        with:
          path: .artifacts
          key: artifacts-${{ hashFiles('**/Artifacts.java') }}

      - name: Setup FFmpeg (${{ runner.os }})
        uses: FedericoCarboni/setup-ffmpeg@v3
        if: ${{ runner.os != 'macOS' }}

      - name: Setup FFmpeg (${{ runner.os }})
        run: |
          brew update
          brew install ffmpeg@7
          brew link ffmpeg@7 --force
          ffmpeg -version
        if: ${{ runner.os == 'macOS' }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build (${{ runner.os }})
        run: ./gradlew build

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4

      - name: Test Report (${{ runner.os }})
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report (${{ runner.os }})
          reporter: java-junit
          path: '**/TEST-*.xml'
